name: CSV and JSON scheduled update

on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          setup-python: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Synchronize the csv file with an up-to-date one
        run: |
          python download.py
          python parse.py
          python parse_twinc.py
          python parse_twinc_en.py
          python parse_structural.py
          python parse2xml.py
          python parse2yaml.py
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kdb-artifacts
          path: |
            kdb.json
            kdb.xml
            kdb.yaml
      - name: Update JSON file
        run: |
          python
      - name: Push and Commit
        run: |
          git add .
          if git diff --exit-code --quiet
          then
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git pull
            git commit -m "update csv and json: $(date +%Y%m%d)" -a
            git push -f origin main
          fi
